# permissions for end users to edit hubbleclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hubblecluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8soperator
    app.kubernetes.io/part-of: k8soperator
    app.kubernetes.io/managed-by: kustomize
  name: hubblecluster-editor-role
rules:
- apiGroups:
  - hubble.example.com
  resources:
  - hubbleclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hubble.example.com
  resources:
  - hubbleclusters/status
  verbs:
  - get
